### PR TITLE
Added: Flowtyp to Cashflowoutput

### PR DESCRIPTION
**Pull request by bmmay**

### CODE REVIEW

**Comment by QuaternionRisk** [comment]
Hi bmmay,

It looks like you are inserting tabs there, can you replace them with spaces please?
There is a clang-format file you can use if you like.

Also, where do the strings "NOM", "IPR", "IND" come from ? I'm wondering if we should use codes like this (3 letters only) or full words "Interest", "Notional", etc.

**Comment by bmmay** [comment]
Hi, 
i'am sorry, the change tab-> space did not work. I will do this again.

I usually use 3 letters for a cashflowtype, there is no reason to use only 3. After you mentioned this, i think its better to use full words, that everyone can understand the output without using a "dictionary".

**Comment by QuaternionRisk** [comment]
What IDE / editor are you using?

**Comment by bmmay** [comment]
MS VS 2015

**Comment by QuaternionRisk** [comment]
Probably easier if you setup MSVS to use spaces instead of tabs
https://msdn.microsoft.com/en-us/library/7sffa753.aspx

Then start again from scratch, it won't re-flow all your code.

**Comment by bmmay** [comment]
Now you should see the changes.

**Comment by QuaternionRisk** [comment]
Hi bmmay,

Can you remove the comments
 //bmayer@AareaL
in the code and instead add your name to the copyright statement at the top, e.g. like you see in QL
https://github.com/lballabio/QuantLib/blob/master/ql/timeseries.hpp

You can use your own name, or company name, or nothing at all, up to you.

I'd prefer not to have comments like this in the code as it will get cluttered very quickly.

**Pull request merged**
