### PR TITLE
Allow linear interpolation in the zero rate in the simulation

### PR DESCRIPTION
**Pull request by stevenvanharen**
This PR is to allow linear interpolation in the zero rate for yield curves during the simulation.

### CODE REVIEW

**Comment by QuaternionRisk** [comment]
Hi Steven, 
many thanks for this, I will merge this now. We have another change for the upcoming release that overlaps with yours a bit (setting up scenario sim market curves as spread curves over the t0 market), but we will definitely keep your linear interpolation option.
Best regards,
Roland

**Comment by QuaternionRisk** [comment]
Oh, I just noticed that your branch has conflicts now with the base branch, after our recent merge activity. Do you have the bandwidth to resolve these conflicts in the next week or two? If not, we can look after your extension while merging the Quaternion/Acadia changes.
Best regards,
Roland
Roland

**Comment by stevenvanharen** [comment]
Hi Roland,

Happy to take a look, I am struggling a bit to spot the conflicts.

This PR appears as having no conflicts to me. Also looked at:
https://github.com/OpenSourceRisk/Engine/compare/master...stevenvanharen:master

I am comparing this incorrectly? Where can I take a look?

Kind Regards,
Steven

**Comment by QuaternionRisk** [comment]
I don't see any conflicts either now. OK, will merge it now.
Kind regards,
Roland

**Pull request merged**
