### PR TITLE
Feature/bond yield shifted

### PR DESCRIPTION
**Pull request by Borgomi42**
implemented new curve which allows to shift a reference curve by an average bond yield spread at duration of the bonds

### CODE REVIEW

**Comment by pcaspers** [comment]
Thanks Oleg! A couple of points:
- can you reduce the inputs in the example, some files are very large (e.g. market data)
- add documentation of new curve config in user guide, motivation / context / references for this approach?
- add read me to the new example
- add description of new example to user guide
- add xml schema for new curve config
- `BondYieldShiftedCurveHelperMarket` looks like a copy of `FittedBondCurveHelperMarket` - do we need both or can we consolidate them into one class?

**Comment by Borgomi42** [comment]
DONE: can you reduce the inputs in the example, some files are very large (e.g. market data)
DONE: BondYieldShiftedCurveHelperMarket looks like a copy of FittedBondCurveHelperMarket - do we need both or can we consolidate them into one class?

working on the other points...

**Comment by Borgomi42** [comment]
DONE: add xml schema for new curve config

**Comment by Borgomi42** [comment]
Done

**Comment by pcaspers** [comment]
sorry for the delay - I am still missing a readme.txt and run.py for the example, also please create an ExpectedOutput folder with suitable results for regression testing

can you also review the docs (some typos) and the example setup (there is no analytic greek in ore, I think this is a custom extension of your ore version)

**Pull request merged**
