### PR TITLE
Add windows GitHub action

### PR DESCRIPTION
**Pull request by kohnech**
This PR add a Windows CI pipeline building with MSVC 14.3. 

Downgraded boost to 1.72 for issue with #160.

I wonder if some with repo settings access can add these 2 CI checks on all contributions to validate and give contributors a badge. :)

Thank you!
kohnech

### CODE REVIEW

**Comment by mgroncki** [comment]
Thanks for the windows CI pipeline. Do you use prebuilt boost packages in the windows build? If so, could you use boost 1.72 instead of 1.83? With boost 1.72 it should work without the patch.

**Comment by kohnech** [comment]
> Thanks for the windows CI pipeline. Do you use prebuilt boost packages in the windows build? If so, could you use boost 1.72 instead of 1.83? With boost 1.72 it should work without the patch.

Thanks for your reply. Good idea, I will try it out. But I tried both compiling boost and the same issue persist but I didn't try 1.72 version.

**Comment by rkapl123** [comment]
There's however the advice in the user guide to use boost 1_78 for building. I made my own bad experiences with using a boost version too low (albeit only in a test project that didn't compile).

**Comment by kohnech** [comment]
> There's however the advice in the user guide to use boost 1_78 for building. I made my own bad experiences with using a boost version too low (albeit only in a test project that didn't compile).

Boost 1.72 means I need to revert to M Visual C++ 2019(MSVC) (14.2) which is not optimal.

**Comment by mgroncki** [comment]
There is no need to downgrade your MSVC, you can use VS2022 with boost 172 v142

**Comment by mgroncki** [comment]
> > Thanks for the windows CI pipeline. Do you use prebuilt boost packages in the windows build? If so, could you use boost 1.72 instead of 1.83? With boost 1.72 it should work without the patch.
> 
> Thanks for your reply. Good idea, I will try it out. But I tried both compiling boost and the same issue persist but I didn't try 1.72 version.

Oh, that’s interesting, when I build boost from scratch (it was boost 1.81) it worked and I thought there is only a problem with the prebuilt boost windows binaries but not a general problem with newer boost versions, since the newer boost versions work on posix systems. I will look into that.

**Comment by kohnech** [comment]
> There's however the advice in the user guide to use boost 1_78 for building. I made my own bad experiences with using a boost version too low (albeit only in a test project that didn't compile).

Boost 1.72 seems be working without the patch. What is the way forward? Should we use boost 1.72 for now and wait for boost to fix the compiler setting? If not then we need apply the patch.

**Comment by mgroncki** [comment]
I think we should be using boost 1.72 with windows if we use the prebuilt binaries.

**Comment by rkapl123** [comment]
I've also built ORE now using 1_72 (after commenting the offending `#include <boost/test/test_tools.hpp>` in OREAnalytics Testsuite) and it went fine. I'm trying to build ORE with the minimum required boost version now.

**Pull request merged**
