### PR TITLE
Upgrade Asian option builder to use new constructor

### PR DESCRIPTION
**Pull request by gbfredrik**
Hi,
Since last year, a new preferred constructor was added to the class `DiscreteAveragingAsianOption` in QuantLib. It mainly changed how the dates of the fixings are passed, so this PR makes the required changes in ORE's Asian option builder to accommodate for that. The PR also includes some simplification of the logic used to read past fixings and cleanup of comments.

All applicable tests pass, still.

Best,
Fredrik
SEB

### CODE REVIEW

**Comment by QuaternionRisk** [comment]
Hi Fredrik, please bear with us over the summer break, we need to do more consolidation on Asians to get your work finally included in ORE. Your are triggering some release of our "internal" stuff, which is really due now. Likewise to include your https://github.com/OpenSourceRisk/Engine/pull/109 
Best regards, Roland

**Comment by gbfredrik** [comment]
Hi Roland and Peter,
Thank you very much for your efforts in merging the PRs so far. Small heads up that I’m on vacation until July 20th, but I’ll help with the questions in the meantime.

1. Moving things from OptionAsianData sounds fine to me. We used to have average-average options but the strikes of those have already been fixed, it’s just average price options now. Neither do we have geometric trades, so perhaps this could even be removed to simplify things? (Unless you want to keep it for the sake of complete coverage). We only have discrete arithmetic and harmonic (which lacks engines) averaging currently.
2. Yes, I’m glad you picked this up. I’ve realized the CommodityUnderlying and the future flags mismatch currently and seemingly get incorrectly applied now. We worked around this by shifting the price curves externally but that is indeed a hassle.
3. Either way is fine to me. Our FX system deals in terms of bought/sold, as we only have average price for FX, but it is a simple transformation so I agree it can be simplified for the average strike option notation to make sense.
4. I know we’ve struggled a little with the FX index at times, so thank you for the clarification. The suggested check sounds good.

For the other points:
1. Regarding the “required fixings”, I know I struggled to figure it out when implementing it. As we only use the pure NPV calculation abilities of ORE, it is sometimes hard to know what effect the date shifting can have when it comes to XVA, etc.
2. For past fixings on continuous Asians, I know some QL engines take the value as an additional argument, whereas the instrument does not. For this, I'm not sure how ORE would read and pass the values correctly. I guess this is an awkward design, and since we only ever used the continuous Asian option config for testing & comparison, it was never a problem for us.

I hope I didn’t miss anything too important now, let me know otherwise and I’ll get back soon :)

**Comment by QuaternionRisk** [comment]
Hi Fredrik, Peter has worked on aligning the asians in the meantime, just pushed the result. I'll merge with your branch here now and close the PR. Please have a look at the result and send us  your feedback. Thanks, Roland

**Comment by gbfredrik** [comment]
Hi,
I've had a chance to ocularly review the changes now. Looks great how the options have been consolidated. Two remarks/questions:
- The FX/EQ Asian option examples in the user guide need updating w.r.t. the AsianData node
- Do you see any possibility of using the newer `DiscreteAveragingAsianOption` constructor (as proposed in this PR) already, or do you propose that further changes would be needed in QL also to suit the use cases you see? This would be beneficial when it comes to #108, for example, as some engines are sensitive to past fixing dates being passed to the ctor (which is what happens now).

Thanks! We may have more findings once we test things further, so I'll make sure to raise issues or submit fixes then. 🙂

**Comment by pcaspers** [comment]
Hi Fredrik, sure, the work so far was only the preparation to allow for more "classic" pricing engines. We just upgraded to QL1.27 internally and so it should be a breeze to integrate #108 now.

**Comment by gbfredrik** [comment]
Sounds good, thanks! FYI that we noticed an issue with the VS build after this merge: the now deleted *asianoption.*pp files are still listed in OREData's project configuration and filters, leading to build errors. 

Best,
Fredrik

**Comment by noonediesalone** [comment]
FYI .. noticed the same :smile: https://github.com/OpenSourceRisk/Engine/commit/7deaf284a424e7500a0258f65102a0e92d2cfba1

**Comment by pcaspers** [comment]
Thanks both. I think we've cleaned that up in the meantime, we will push this out soon.

**Pull request merged**
